# Generated by Django 3.1.7 on 2021-03-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_time',
            new_name='timestamp',
        ),
    ]
