# Generated by Django 3.1.7 on 2021-03-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210328_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
