# Generated by Django 3.1.7 on 2021-03-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_responsecode_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsecode',
            name='user_agent',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
