# Generated by Django 3.1.7 on 2021-03-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_responsecode_user_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsecode',
            name='user_agent',
        ),
    ]
